### ISSUE TITLE
[API response issue] 'TheCode' fields are all 'None'

### ISSUE THREAD

**Issue by hnguyentt** [ICD-API/Python-samples#2]
Hi,
I want to get the ICD code of the disease "retinal artery occlusion". 
API-version: v2
When I use *URI = "https://id.who.int/icd/entity/search?q='retinal artery occlusion'"*, all the 'TheCode' fields in the response are "None", like this:
{'DestinationEntities': [{'Id': 'http://id.who.int/icd/entity/613330234',
   'Title': "Central <em class='found'>retinal</em> <em class='found'>artery</em> <em class='found'>occlusion</em>",
   'PropertiesTruncated': False,
   'IsResidualOther': False,
   'IsResidualUnspecified': False,
   'Chapter': '09',
   'TheCode': None,
   'Score': 0.0001232716,
   'TitleIsASearchResult': True,
   'TitleIsTopScore': True,
   'EntityType': 0,
   'Important': False,
   'Descendants': [{'Id': 'http://id.who.int/icd/entity/1103454380',
     'Title': "Transient <em class='found'>retinal</em> <em class='found'>artery</em> <em class='found'>occlusion</em>",
     'PropertiesTruncated': False,
     'IsResidualOther': False,
     'IsResidualUnspecified': False,
     'Chapter': '09',
     'TheCode': None,
     'Score': 0.0001232716,
     'TitleIsASearchResult': True,
     'TitleIsTopScore': True,
     'EntityType': 0,
     'Important': False,
     'Descendants': [],
     'StemId': 'http://id.who.int/icd/entity/1103454380',
     'IsLeaf': True,
     'PostcoordinationAvailability': 0,
     'HasCodingNote': False,
     'HasMaternalChapterLink': False,
     'MatchingPVs': []}],
   'StemId': 'http://id.who.int/icd/entity/613330234',
   'IsLeaf': False,
   'PostcoordinationAvailability': 0,
   'HasCodingNote': False,
   'HasMaternalChapterLink': False,
   'MatchingPVs': [{'PropertyId': 'Synonym',
     'Label': "CRAO - [central <em class='found'>retinal</em> <em class='found'>artery</em> <em class='found'>occlusion</em>]",
     'Score': 1.02865834e-10,
     'Important': False}]},
  {'Id': 'http://id.who.int/icd/entity/1552912714',
   'Title': "<em class='found'>Retinal</em> <em class='found'>artery</em> branch <em class='found'>occlusion</em>",
   'PropertiesTruncated': False,
   'IsResidualOther': False,
   'IsResidualUnspecified': False,
   'Chapter': '09',
   'TheCode': None,
   'Score': 0.0001232716,
   'TitleIsASearchResult': True,
   'TitleIsTopScore': True,
   'EntityType': 0,
   'Important': False,
   'Descendants': [],
   'StemId': 'http://id.who.int/icd/entity/1552912714',
   'IsLeaf': True,
   'PostcoordinationAvailability': 0,
   'HasCodingNote': False,
   'HasMaternalChapterLink': False,
   'MatchingPVs': [{'PropertyId': 'NarrowerTerm',
     'Label': "Partial <em class='found'>retinal</em> <em class='found'>artery</em> <em class='found'>occlusion</em>",
     'Score': 0.0001232716,
     'Important': False}]}],
 'Error': False,
 'ErrorMessage': None,
 'ResultChopped': False,
 'WordSuggestionsChopped': False,
 'GuessType': 1,
 'UniqueSearchId': 'dad372cc-9c43-4777-a5d3-5bd706624cbb',
 'Words': None}

Checking for other diseases, I also faced the same issue. Please give me some workarounds.

**Comment by MITEL-UNIUD** [comment]
You are searching in the Foundation layer of the classification, which does not carry codes. If you need the code, which belongs to the Mortality&Morbidity Statistics linearization, you must change the endpoint to 
`https://id.who.int/icd/release/11/2019-04/mms/search?q=retinal%20artery%20occlusion`

**Comment by hnguyentt** [comment]
> You are searching in the Foundation layer of the classification, which does not carry codes. If you need the code, which belongs to the Mortality&Morbidity Statistics linearization, you must change the endpoint to
> `https://id.who.int/icd/release/11/2019-04/mms/search?q=retinal%20artery%20occlusion`

Thank you for your help.

These codes seem to belong to ICD11. How can I get the ICD10 code of the disease? I try to change the version and release date but it did not work.

**Comment by MITEL-UNIUD** [comment]
There is no Search API for ICD-10, it is a feature specific of ICD-11, which was born with information systems in mind.

**Comment by hnguyentt** [comment]
I got it. Thank you for your help.
