### ISSUE TITLE
Code not received 

### ISSUE THREAD

**Issue by DanielXing1103** [ICD-API/Python-samples#7]
I hope this message finds you well. We are currently working on a project to develop a learning app for medical coders to learn ICD 11 codes.

I'm encountering an issue with retrieving the actual four-digit codes representing specific conditions using the API. For instance, when I queried information for Cholera using the URI "http://id.who.int/icd/entity/257068234", and followed the Python example on your GitHub repo, I didn't receive the actual "Code" in the JSON response.

Could you please assist me in resolving this issue? Any clarification or guidance you can provide would be greatly appreciated.

Thank you for your time and assistance.

**Comment by rodhric** [comment]
Hi, well, let me understand. What exactly would you want to do with the 4-first codes?

**Comment by MITEL-UNIUD** [comment]
Are you querying the Foundation or the Linearizations? In the Foundation layer there aren't codes; if you need the actual code, you have to query MMS (ICD-11 Mortality and Morbidity Statistics). You can refer to the current, up-to-date documentation here: https://icd.who.int/icdapi . 
However, as a side comment, if the app is for learning, remember that you can code only with terminal codes (leaves of the tree), not mid level groups and categories.

**Comment by DanielXing1103** [comment]
Thank you very much! Querying the Linearization uri helped me retrieve the code.
